org: yeukfei05
app: sweet-factory-backend-serverless
service: sweet-factory-backend-serverless

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-southeast-1
  apiName: sweet-factory-backend-serverless-prod
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: production
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
    JWT_SECRET: ${param:JWT_SECRET}
    DATABASE_URL: ${param:DATABASE_URL}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: sweet factory backend serverless
  lambdaHashingVersion: 20201221
  # architecture: arm64
  timeout: 30

functions:
  graphql:
    handler: src/graphql/handler.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-prune-plugin
  - serverless-plugin-typescript
  - serverless-offline

custom:
  prune:
    automatic: true
    number: 3
